-- ============================================================
-- Ejecutar como: TUKUNAFUNC (después de 06_DDL_INPUT_FIELDS.sql)
-- Inserta los campos de entrada para ECUABET y BET593 en QA.
-- Basado en el JSON de develop (puerto 8085, 2026-06-12).
--
-- Valores QA confirmados (2026-06-12):
--   ECUABET  category=983  subcategory=1118(CI) / 1119(CO)  svc=12661912
--   BET593   category=983  subcategory=1120(CI) / 1121(CO)  svc=408403
-- ============================================================

-- -------------------------------------------------------
-- ECUABET CASH_IN (1118 / 12661912 / 100713841)
-- PRECHECK: amount obligatorio + document/phone/userid opcionales (OR)
-- -------------------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '983', '1118', '12661912', '100713841',
    'amount', 'Monto Recarga', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '983', '1118', '12661912', '100713841',
    'document', 'Documento Usuario', 'STRING', 'PRECHECK', 0, 'IDENTIFICATION', 'OR', 2);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '983', '1118', '12661912', '100713841',
    'phone', 'Celular Usuario', 'STRING', 'PRECHECK', 0, 'IDENTIFICATION', 'OR', 3);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '983', '1118', '12661912', '100713841',
    'userid', 'ID Usuario', 'STRING', 'PRECHECK', 0, 'IDENTIFICATION', 'OR', 4);

-- -------------------------------------------------------
-- ECUABET CASH_OUT (1119 / 12661912 / 100708846)
-- PRECHECK: amount + password + withdrawId
-- -------------------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '983', '1119', '12661912', '100708846',
    'amount', 'Monto', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '983', '1119', '12661912', '100708846',
    'password', 'Contraseña asignado a retiro', 'STRING', 'PRECHECK', 1, 'PASS', NULL, 2);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '983', '1119', '12661912', '100708846',
    'withdrawId', 'Número asignado a retiro', 'STRING', 'PRECHECK', 1, 'ID', NULL, 3);

-- -------------------------------------------------------
-- BET593 CASH_IN (1120 / 408403 / 100708850)
-- EXECUTE: amount + document
-- REVERSE: document + motivo
-- -------------------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '983', '1120', '408403', '100708850',
    'amount', 'Monto Recarga', 'DOUBLE', 'EXECUTE', 1, 'AMOUNT', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '983', '1120', '408403', '100708850',
    'document', 'Documento Usuario', 'STRING', 'EXECUTE', 1, 'IDENTIFICATION', NULL, 2);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '983', '1120', '408403', '100708850',
    'document', 'Cuenta web', 'STRING', 'REVERSE', 1, 'IDENTIFICATION', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '983', '1120', '408403', '100708850',
    'motivo', 'Motivo del reverso', 'STRING', 'REVERSE', 1, 'DETAIL', NULL, 2);

-- -------------------------------------------------------
-- BET593 CASH_OUT (1121 / 408403 / 100708848)
-- PRECHECK: amount + document + withdrawId
-- -------------------------------------------------------
INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '983', '1121', '408403', '100708848',
    'amount', 'Monto', 'DOUBLE', 'PRECHECK', 1, 'AMOUNT', NULL, 1);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '983', '1121', '408403', '100708848',
    'document', 'Documento Usuario', 'STRING', 'PRECHECK', 1, 'IDENTIFICATION', NULL, 2);

INSERT INTO TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
    (ID_FIELD, CATEGORY_CODE, SUBCATEGORY_CODE, SERVICE_PROVIDER_CODE, RMS_ITEM_CODE,
     FIELD_ID, LABEL, FIELD_TYPE, CAPABILITY, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR, FIELD_ORDER)
VALUES (SEQ_IN_OMNI_INPUT_FIELDS.NEXTVAL,
    '983', '1121', '408403', '100708848',
    'withdrawId', 'Numero asignado a retiro', 'STRING', 'PRECHECK', 1, 'ID', NULL, 3);

COMMIT;

-- Verificar:
-- SELECT SUBCATEGORY_CODE, RMS_ITEM_CODE, CAPABILITY, FIELD_ORDER, FIELD_ID, LABEL, IS_REQUIRED, FIELD_GROUP, CONDITIONAL_OPERATOR
--   FROM TUKUNAFUNC.IN_OMNI_INPUT_FIELDS
--  ORDER BY SUBCATEGORY_CODE, CAPABILITY, FIELD_ORDER;
